### PR TITLE
Replace database field name

### LINKED ISSUE #167: sw:generate  => Code: 42S22,1054,Unknown column 'articleID' in 'field list'
Error Message:
```
In DatabaseWriter.php line 55:
                                                                                                              
  Failed to execute LOAD DATA LOCAL INFILE '/var/www/html/output/articles_attributes.csv' IGNORE INTO TABLE   
  s_articles_attributes                                                                                       
  FIELDS TERMINATED BY ',' LINES TERMINATED BY '\n'                                                           
  (`articleID`, `articledetailsID`);                                                                          
                                                                                                              
  Code: 42S22,1054,Unknown column 'articleID' in 'field list'                                                 
```                                                                  

In my test-database, there is no `articleID`:

```
CREATE TABLE `s_articles_attributes` (
  `id` int(11) NOT NULL,
  `articledetailsID` int(11) UNSIGNED DEFAULT NULL,
  `attr1` text COLLATE utf8_unicode_ci DEFAULT NULL,
  `attr2` text COLLATE utf8_unicode_ci DEFAULT NULL,
  `attr3` text COLLATE utf8_unicode_ci DEFAULT NULL,
  `attr4` text COLLATE utf8_unicode_ci DEFAULT NULL,
  `attr5` text COLLATE utf8_unicode_ci DEFAULT NULL,
  `attr6` text COLLATE utf8_unicode_ci DEFAULT NULL,
  `attr7` text COLLATE utf8_unicode_ci DEFAULT NULL,
  `attr8` text COLLATE utf8_unicode_ci DEFAULT NULL,
  `attr9` text COLLATE utf8_unicode_ci DEFAULT NULL,
  `attr10` text COLLATE utf8_unicode_ci DEFAULT NULL,
  `attr11` text COLLATE utf8_unicode_ci DEFAULT NULL,
  `attr12` text COLLATE utf8_unicode_ci DEFAULT NULL,
  `attr13` text COLLATE utf8_unicode_ci DEFAULT NULL,
  `attr14` text COLLATE utf8_unicode_ci DEFAULT NULL,
  `attr15` text COLLATE utf8_unicode_ci DEFAULT NULL,
  `attr16` text COLLATE utf8_unicode_ci DEFAULT NULL,
  `attr17` text COLLATE utf8_unicode_ci DEFAULT NULL,
  `attr18` text COLLATE utf8_unicode_ci DEFAULT NULL,
  `attr19` text COLLATE utf8_unicode_ci DEFAULT NULL,
  `attr20` text COLLATE utf8_unicode_ci DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
```

### PR DESCRIPTION
**Pull request by kkrieger85**
may fix #167 

I am not sure, if this depends on SW version

### CODE REVIEW

File: src/Extensions/Shopware/DataGenerator/Services/LoadDataInfile.php [hunk 1]
```diff
@@ -83,7 +83,7 @@ class LoadDataInfile
         's_articles_categories' => ['articleID', 'categoryID'],
         's_media' => ['id', 'albumID', 'name', 'path', 'type', 'extension', 'created'],
         's_articles_img' => ['articleID', 'img', 'main', 'extension', 'media_id'],
-        's_articles_attributes' => ['articleID', 'articledetailsID'],
+        's_articles_attributes' => ['id', 'articledetailsID'],
```
Comment (shyim) [inline src/Extensions/Shopware/DataGenerator/Services/LoadDataInfile.php:86]: You can just remove articleID :thinking: . Its since 5.2 null

Comment (mitelg) [reply src/Extensions/Shopware/DataGenerator/Services/LoadDataInfile.php:86]: correct. so remove it, and we are happy to merge your fix :blush:

**Comment by mitelg** [comment]
thanks for your contribution @kkrieger85 👍🎉💙
